name-template: '$NEXT_PATCH_VERSION.RELEASE'
tag-template: '$NEXT_PATCH_VERSION.RELEASE' 
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
template: |
  ## Changes

  $CHANGES

  ## 🕵️ Full commit logs

  https://github.com/mskcc/smile-server/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION.RELEASE
