name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker build . --file Dockerfile --tag cmometadb/smile-server:${{ github.ref_name }}
    - name: push image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push cmometadb/smile-server:${{ github.ref_name }}
      
